# Generated by Django 3.2.4 on 2023-09-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('idClientes', models.IntegerField(db_column='idClientes', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('Apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('Correo_Electronico', models.CharField(db_column='Correo Electronico', max_length=100)),
                ('Telefono', models.IntegerField(db_column='Telefono')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
