# Generated by Django 3.2.4 on 2023-09-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('idDireccion', models.IntegerField(db_column='idDireccion', primary_key=True, serialize=False)),
                ('colonia', models.CharField(db_column='colonia', max_length=100)),
                ('ciudad', models.CharField(db_column='ciudad', max_length=100)),
                ('Municipio', models.CharField(db_column='Municipio', max_length=100)),
                ('Estado', models.CharField(db_column='Estado', max_length=100)),
                ('COdigoPostal', models.CharField(db_column='COdigoPostal', max_length=100)),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
    ]
