# Generated by Django 3.2.4 on 2023-09-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaCliente',
            fields=[
                ('idEtiquetaCliente', models.IntegerField(db_column='idEtiquetaCliente', primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(db_column='etiqueta', max_length=100, unique=True)),
            ],
        ),
    ]
