# Generated by Django 3.2.4 on 2023-09-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_etiquetacliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.IntegerField(db_column='idEstado', primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='estado', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Estado',
            },
        ),
        migrations.AlterModelTable(
            name='etiquetacliente',
            table='EtiquetaCliente',
        ),
    ]
