# Generated by Django 3.2.4 on 2023-09-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230919_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades_Compra',
            fields=[
                ('idActvidadesCliente', models.IntegerField(db_column='idActvidadesCliente', primary_key=True, serialize=False)),
                ('categoria', models.CharField(db_column='categoria', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Actividades_Compra',
            },
        ),
    ]
