# Generated by Django 3.2.4 on 2023-09-19 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_actividades_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('idNota', models.IntegerField(db_column='idNota', primary_key=True, serialize=False)),
                ('Fecha', models.DateField(db_column='Fecha')),
                ('Nota', models.CharField(db_column='categoria', max_length=1000)),
                ('FKidClientes', models.ForeignKey(db_column='FKidClientes', on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
            ],
            options={
                'db_table': 'Nota',
            },
        ),
    ]
