# Generated by Django 3.2.4 on 2023-09-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Correo_Electronico',
            field=models.EmailField(db_column='Correo Electronico', max_length=100),
        ),
    ]
