# Generated by Django 3.2.4 on 2023-09-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_clientes_correo_electronico'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteraccionCliente',
            fields=[
                ('idInteCliente', models.IntegerField(db_column='idInteCliente', primary_key=True, serialize=False)),
                ('Fecha', models.DateField(db_column='Fecha')),
                ('FKEtiquetaCliente', models.ForeignKey(db_column='FKEtiquetaCliente', on_delete=django.db.models.deletion.CASCADE, to='api.etiquetacliente')),
                ('FKidClientes', models.ForeignKey(db_column='FKidClientes', on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
            ],
            options={
                'db_table': 'InteraccionCliente',
            },
        ),
    ]
