# Generated by Django 3.2.4 on 2023-09-19 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion_Clientes',
            fields=[
                ('idDireccion_Clientes', models.IntegerField(db_column='Direccion_Clientes', primary_key=True, serialize=False)),
                ('FKclientes', models.ForeignKey(db_column='FKclientes', on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('FKidDireccion', models.ForeignKey(db_column='FKidDireccion', on_delete=django.db.models.deletion.CASCADE, to='api.direccion')),
            ],
        ),
    ]
